In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency,f_oneway
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
df = pd.read_csv("modeldf.csv")

In [3]:
numcols = df.select_dtypes(include=["int64","float64"]).columns.tolist()
numcols.remove("prospectid")
catcols = df.select_dtypes(include=["object","category"]).columns.tolist()

In [4]:
numdf = df[numcols]

In [5]:

columns_to_be_kept_numerical = []
col_name = []
p_val = []

for i in numcols:
    a = list(numdf[i])  
    b = list(df['approved_flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        col_name.append(i)
        p_val.append(p_value)
        columns_to_be_kept_numerical.append(i)

In [6]:
pd.DataFrame({"col_name":col_name,"p_value":p_val})

                  col_name        p_value
0                 total_tl   0.000000e+00
1            tot_closed_tl   0.000000e+00
2            tot_active_tl   0.000000e+00
3      total_tl_opened_l6m  2.497223e-288
4        tot_tl_closed_l6m   1.118279e-83
..                     ...            ...
69  pct_pl_enq_l6m_of_ever   0.000000e+00
70  pct_cc_enq_l6m_of_ever   0.000000e+00
71                 hl_flag  3.134991e-309
72                 gl_flag  5.630245e-310
73            credit_score   0.000000e+00

[74 rows x 2 columns]

In [7]:
after_anova = numdf[columns_to_be_kept_numerical]

In [8]:
vif_data = numdf[columns_to_be_kept_numerical]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
vif = []
column_index = 0

for i in range (0,total_columns):
    
    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)
    
    
    if vif_value <= 6:
        columns_to_be_kept.append( columns_to_be_kept_numerical[i] )
        vif.append(vif_value)
        column_index = column_index+1
    
    else:vif_data = vif_data.drop([ columns_to_be_kept_numerical[i] ] , axis=1)

c:\Users\Rahul\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

c:\Users\Rahul\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 10.826309160519477
0 --- 8.267473878266372
0 --- 6.4255404537202265
0 --- 5.4398691177839735
1 --- 2.49689768477769

c:\Users\Rahul\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 2303.3492284907684
2 --- 8.02867192222403
2 --- 3.6724433377526773
3 --- 5.909416509158427
4 --- 5.067180668211875
5 --- 1.9638695967500106

c:\Users\Rahul\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

6 --- inf
6 --- 4.748446843152039
7 --- 21.078837350044044
7 --- 31.434448802400233
7 --- 4.456062154299317
8 --- 2.999419989861085
9 --- 2.8125545945228816
10 --- 4.037181901527773
11 --- 2.175073134313329
12 --- 5.211691144665633
13 --- 5.6514239422189005
14 --- 3.7841750489540393
15 --- 17.837408927351866
15 --- 5.769660711849322
16 --- 8.453850611166107
16 --- 4.334426460737456
17 --- 6.6830177146072405

c:\Users\Rahul\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

17 --- inf
17 --- 9.398565085822588
17 --- 1.7882794041690564
18 --- 3.1791632542643433
19 --- 4.59013804586891
20 --- 8.561136113319217
20 --- 1.9603210049635844
21 --- 7.112880843982636
21 --- 15.394350226865214
21 --- 1.8525908787938041
22 --- 1.558596231582836
23 --- 1.4753165217826516
24 --- 2.1339065583894428
25 --- 2.0703757629929678
26 --- 1.0113726061193167
27 --- 2.7798915246511755
28 --- 16.616631821128962
28 --- 6.284528631226689
28 --- 8.756390557537102
28 --- 2.3600574518800683
29 --- 8.446920249301305
29 --- 12.914379294290626
29 --- 3.466489914523604
30 --- 2.0330921680952607
31 --- 17.95890964806216
31 --- 10.617981866831562
31 --- 2.3660772181251057
32 --- 21.82576943088723
32 --- 2.880078382217181
33 --- 3.414527395484565
34 --- 10.22082410835256
34 --- 7.053473913614322
34 --- 2.504216696429184
35 --- 3.090214668209727
36 --- 22.980828831806033
36 --- 2.740154525912153
37 --- 20.837655891428764
37 --- 16.584905617721216
37 --- 1.7716655041259393
38 --- 1.5622132249467793
39 --- 1.9815787437813126
40 --- 4.39497660086577
41 --- 18.988820718453923

In [9]:
pd.DataFrame({"col_name":columns_to_be_kept,"vif_val":vif})

                        col_name   vif_val
0                pct_tl_open_l6m  5.439869
1              pct_tl_closed_l6m  2.496898
2             tot_tl_closed_l12m  3.672443
3               pct_tl_open_l12m  5.909417
4             pct_tl_closed_l12m  5.067181
5                tot_missed_pmnt  1.963870
6                          cc_tl  4.748447
7                        home_tl  4.456062
8                          pl_tl  2.999420
9                     secured_tl  2.812555
10                  unsecured_tl  4.037182
11                      other_tl  2.175073
12                 age_oldest_tl  5.211691
13                 age_newest_tl  5.651424
14     time_since_recent_payment  3.784175
15  time_since_recent_deliquency  5.769661
16         max_delinquency_level  4.334426
17             num_deliq_6_12mts  1.788279
18                max_deliq_6mts  3.179163
19               max_deliq_12mts  4.590138
20             num_times_60p_dpd  1.960321
21                 num_std_12mts  1.852591
22                       num_sub  1.558596
23                 num_sub_12mts  1.475317
24                       num_dbt  2.133907
25                 num_dbt_12mts  2.070376
26                       num_lss  1.011373
27         recent_level_of_deliq  2.779892
28                   cc_enq_l12m  2.360057
29                   pl_enq_l12m  3.466490
30         time_since_recent_enq  2.033092
31                       enq_l3m  2.366077
32              netmonthlyincome  2.880078
33           time_with_curr_empr  3.414527
34                cc_utilization  2.504217
35                       cc_flag  3.090215
36                       pl_flag  2.740155
37        pct_pl_enq_l6m_of_ever  1.771666
38        pct_cc_enq_l6m_of_ever  1.562213
39                       hl_flag  1.981579
40                       gl_flag  4.394977

In [ ]:
Z

In [31]:
ready = df[columns_to_be_kept +catcols]

In [32]:
ready.to_csv("model_build.csv",index=False)